[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile.prod"
buildContext = "backend"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300 