[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile.minimal"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 60 