"""Initial migration with all models

Revision ID: b9a61fb77812
Revises: 
Create Date: 2025-06-03 13:16:06.198526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a61fb77812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('paper_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('s3_path', sa.String(), nullable=True),
    sa.Column('size_mb', sa.Float(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('model_metadata', sa.JSON(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=False)
    op.create_table('model_deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('deployment_type', sa.Enum('SERVERLESS', 'CONTAINER', 'ENDPOINT', name='deploymenttype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'BUILDING', 'DEPLOYING', 'RUNNING', 'FAILED', 'STOPPED', 'UPDATING', name='deploymentstatus'), nullable=True),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('internal_url', sa.String(), nullable=True),
    sa.Column('cpu_limit', sa.Float(), nullable=True),
    sa.Column('memory_limit', sa.Integer(), nullable=True),
    sa.Column('max_replicas', sa.Integer(), nullable=True),
    sa.Column('min_replicas', sa.Integer(), nullable=True),
    sa.Column('environment_vars', sa.JSON(), nullable=True),
    sa.Column('deployment_config', sa.JSON(), nullable=True),
    sa.Column('health_check_path', sa.String(), nullable=True),
    sa.Column('build_logs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('auto_scale_enabled', sa.Boolean(), nullable=True),
    sa.Column('scale_up_threshold', sa.Float(), nullable=True),
    sa.Column('scale_down_threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_deployments_id'), 'model_deployments', ['id'], unique=False)
    op.create_index(op.f('ix_model_deployments_name'), 'model_deployments', ['name'], unique=False)
    op.create_index(op.f('ix_model_deployments_status'), 'model_deployments', ['status'], unique=False)
    op.create_table('deployment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('log_level', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_logs_id'), 'deployment_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_logs_id'), table_name='deployment_logs')
    op.drop_table('deployment_logs')
    op.drop_index(op.f('ix_model_deployments_status'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_name'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_id'), table_name='model_deployments')
    op.drop_table('model_deployments')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 