"""add username column

Revision ID: c81ebe60574e
Revises: 002
Create Date: 2025-05-30 11:44:03.883097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c81ebe60574e'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_versions', 'changelog',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('model_versions', 's3_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_versions', 'size_mb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('model_versions', 'format',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_versions', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.drop_constraint('model_versions_model_id_fkey', 'model_versions', type_='foreignkey')
    op.create_foreign_key(None, 'model_versions', 'models', ['model_id'], ['id'])
    op.add_column('models', sa.Column('framework', sa.String(), nullable=True))
    op.add_column('models', sa.Column('task_type', sa.String(), nullable=True))
    op.add_column('models', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('models', sa.Column('license', sa.String(), nullable=True))
    op.add_column('models', sa.Column('paper_url', sa.String(), nullable=True))
    op.add_column('models', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('models', sa.Column('downloads', sa.Integer(), nullable=True))
    op.add_column('models', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('models', sa.Column('average_rating', sa.Float(), nullable=True))
    op.alter_column('models', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_models_name', table_name='models')
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.drop_constraint('models_owner_id_fkey', 'models', type_='foreignkey')
    op.create_foreign_key(None, 'models', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.create_foreign_key('models_owner_id_fkey', 'models', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.create_index('ix_models_name', 'models', ['name'], unique=False)
    op.alter_column('models', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('models', 'average_rating')
    op.drop_column('models', 'likes')
    op.drop_column('models', 'downloads')
    op.drop_column('models', 'github_url')
    op.drop_column('models', 'paper_url')
    op.drop_column('models', 'license')
    op.drop_column('models', 'tags')
    op.drop_column('models', 'task_type')
    op.drop_column('models', 'framework')
    op.drop_constraint(None, 'model_versions', type_='foreignkey')
    op.create_foreign_key('model_versions_model_id_fkey', 'model_versions', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.alter_column('model_versions', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_versions', 'format',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_versions', 'size_mb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('model_versions', 's3_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_versions', 'changelog',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ### 